refactor: refactor type constants
TeamNado-Sunbae/NadoSunbae-Server pull request #320
Opened 2022-08-07 17:28 UTC by seoljiwon

- closes #303 

- [ ] type constants refactor
- [ ] front한테 받는 params, query, body에서 id -> str로 변경
- [ ] likeDB `post_id -> target_id`, `post_type_id -> target_type_id`
- [ ] relation_review_tag DB `post_id -> review_id`
- [ ] inappropriate_review DB `post_id -> review_id`
- [ ] report DB `reported_target_id -> target_id`, `reported_target_type_id -> target_type_id`

---
- [ ] params, query, body 관련 노션 정리
- [ ] 실제 DB 컬럼명 변경
- [ ] like DB post_type_id = 2, 3, 4 -> 2로 UPDATE 하는 쿼리 실행

2022-08-08 06:31 UTC, wngus4296 requested changes
8/8 오전 1차로 확인했습니다.
제 pr에서 like data나 제안해주셨던 tagname까지 한 번의 쿼리에서 같이 가져오게끔 쿼리 수정해보겠습니다.
그 이후에 여기도 비슷하게 반영하면 좋을 것 같아요!

2022-08-08 14:59 UTC, seoljiwon commented on functions/api/routes/post/postMajorListGET.js
> +    }
제안 감사합니다! 이거 비슷한 코드가 다른 곳에도 많은데 break;혹시 실수하면 default가 에러 반환이라 위험할 거 같아서 일단은 그대로 둘게용

2022-08-08 15:00 UTC, seoljiwon commented on functions/api/routes/review/reviewListPOST.js
>      if (reviewList.length === 0) {
이거 따로 이슈 있는 거 맞죠? 머지 후에 관련된 거 이슈 달아서 한 번에 싹 없앨까요?

2022-08-08 16:03 UTC, eunji8784 commented on functions/api/routes/user/userMypageCommentListGET.js
> -    // 마이페이지 주인장 id
아놔 이거 내가 쓴 건데 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-08-09 02:43 UTC, seoljiwon commented
> 8/8 오전 1차로 확인했습니다. 제 pr에서 like data나 제안해주셨던 tagname까지 한 번의 쿼리에서 같이 가져오게끔 쿼리 수정해보겠습니다. 그 이후에 여기도 비슷하게 반영하면 좋을 것 같아요!

쿼리 관련 개선은 신기능 도입할 때 하거나 다른 refactor branch에서 할 예정입니다. 여기서는 PR에 적힌 부분 위주로 봐주세요!
like type 변경하면서 가져오는 쿼리가 많이 바뀌어서 제가 신기능도 조금만 구현해놓긴 했는데 완벽하지 않은 부분은 다 이슈로 달아놨기 때문에 쿼리 개선 등등은 그쪽 브랜치에서 할 예정입니다!

2022-08-09 07:46 UTC, merged