create post, update post
TeamNado-Sunbae/NadoSunbae-Server pull request #345
Opened 2022-08-10 08:39 UTC by seoljiwon

- closes #324 

- 커뮤티니와 1:1 질문에서 모두 사용할 수 있게 했습니다.
- post PUT refactor

2022-08-13 13:47 UTC, wngus4296 requested changes
리뷰 확인 부탁드립니당

2022-08-13 13:47 UTC, wngus4296 commented on functions/api/routes/post/postPUT.js
> +    );
여기 isLiked는 필요없나요!?

2022-08-13 13:53 UTC, wngus4296 requested changes

2022-08-13 13:53 UTC, wngus4296 commented on functions/api/routes/post/postPOST.js
> +      postTypeId;
이 친구의 type은  따로 지정 안한 이유가 있을까요??

2022-08-13 13:53 UTC, wngus4296 commented on functions/api/routes/post/postPOST.js
>  const slackAPI = require("../../../middlewares/slackAPI");
이 코드는 없어도 될 것 같습니다!

2022-08-15 13:26 UTC, seoljiwon commented on functions/api/routes/post/postPUT.js
> +    );
게시글 수정 뷰인데 다른 정보들 안 쓰던 거 같아서(join 안 쓰고 좀 더 빨리 return 하도록) 변경 관련되는 내용 위주로만 가져왔습니다!

2022-08-15 13:27 UTC, seoljiwon commented on functions/api/routes/post/postPOST.js
> +      postTypeId;
이유가 없져 실수입니다 감사합니다 ㅎㅎ

2022-08-15 13:29 UTC, seoljiwon commented on functions/api/routes/post/postPOST.js
>  const slackAPI = require("../../../middlewares/slackAPI");
이거 더미 트래킹에 사용하고 있어서 남겨둘게용

2022-08-15 14:20 UTC, wngus4296 approved these changes
어푸룹 드려여~

2022-08-15 14:45 UTC, merged